### ISSUE TITLE
Can't exclude packages using coverage.list

### ISSUE THREAD

**Issue by mdavidovichHst** [intersystems/TestCoverage#16]
Hi there, I have tried doing this multiple ways on coverage.list but I am still getting coverage report data for the HS package and sub-packages and also the TestCoverage package.  Here's a snap of my coverage.list:

![image](https://user-images.githubusercontent.com/103590728/169389019-1040ae27-9537-4c13-bebd-68a165d37ceb.png)

And here is the output on Jenkins:

![image](https://user-images.githubusercontent.com/103590728/169389097-2262727e-0edf-4c1e-bedc-c01f8a2117e2.png)

I've tried:
-HS
-HS.PKG
-HS.FHIR
-HS.FHIR.PKG
 . . . and so on.

I know I can't use the wildcard for packages but I've tried excluding both the top level package and the exact sub-package with and without the .PKG marker.

Have I missed a key step or is this a error in the tool?

Thanks!

**Comment by mdavidovichHst** [comment]
Just to mention, I believe this is making the test coverage run very slow. Jenkins reports over two minutes for the report to produce.  Trying to get this time down by excluding unnecessary classes.

**Comment by mdavidovichHst** [comment]
Issue resolved by ONLY listing includes.

**Comment by mdavidovichHst** [comment]
Sorry, I have to reopen.  

I have a package PR and there's a subpackage PR.UnitTest.

My file has
PR.PKG
-PR.Unit

**Comment by mdavidovichHst** [comment]
Sorry have to reopen: I'm almost there but now I notice that I have a package with about 12 sub-packages.  The high-level package Interface is tracked but only three of the subpackages are tracked.  All subpackages have class files in them.

Any way to fix this?

**Comment by isc-tleavitt** [comment]
@mdavidovichHst can you paste in the coverage.list?

**Comment by isc-tleavitt** [comment]
Another thought - might you have multiple files named coverage.list in your unit test directory structure that might be conflicting?

**Comment by isc-tleavitt** [comment]
re: subpackages not being tracked, if they were just (e.g.) Ensemble message classes with properties and no methods, there'd be nothing to track code coverage on so they wouldn't show up.

**Comment by mdavidovichHst** [comment]
> Another thought - might you have multiple files named coverage.list in your unit test directory structure that might be conflicting?

No just the one file in the root!

> @mdavidovichHst can you paste in the coverage.list?

```
// Include all application code
AD.PKG
Core.PKG
DataShare.PKG
DefaultAcceptMessageService.PKG
EN.PKG
HX.PKG
Interface.PKG
LB.PKG
PR.PKG
RP.PKG
Studio.PKG
SY.PKG
User.PKG

// Exclude
-PR.UnitTest.PKG
-RP.UnitTest.PKG
-LB.UnitTest.PKG

```
> re: subpackages not being tracked, if they were just (e.g.) Ensemble message classes with properties and no methods, there'd be nothing to track code coverage on so they wouldn't show up.

Ok this makes sense and is confirmed.  However there's a class with no properties and one instance method.  Would that be tracked?
