### ISSUE TITLE
Test results link not providing full server address name

### ISSUE THREAD

**Issue by JimmySting** [intersystems/TestCoverage#2]
First off: this is a great tool!

When running Test Coverage tool on a project's Development environment, the provided web link at the end of the run doesn't have correct server address.

Example URL:
`http://server123:8080/csp/odxi/TestCoverage.UI.AggregateResultViewer.cls?Index=2`

Where `server123` is only part of the full server address. Something like `server123.ds.ws.com` is expected.

The Test Coverage tool is using the following line to gather the web server information:

`Set tSC = ##class(%RoutineMgr).GetWebServerPort(.tPort,.tServer,.tURLPrefix)`

which ends up calling:

`##class(%Studio.General).GetWebServerPort(.port,.server,.urlprefix,.url)`

`tServer` in this case resolves to `server123`.

I'm not sure if this is something that is user configured somewhere and we would need to make some sort of system change. Or if the methods use aren't always adequate for resolving the full server name. For instance, the link produced by the tool works fine on my local instance.

**Comment by timleavitt** [comment]
@JimmySting  I've added a note on this configuration option mentioned above under "Viewing Results" in the readme.
