### ISSUE TITLE
The code coverage statistics are inaccurate in certain specific scenarios.

### ISSUE THREAD

**Issue by EnRyu123** [intersystems/TestCoverage#33]
Is there a way to ensure that the code sending messages through **BusinessService** or **BusinessProcess** can be fully tracked? 
The current issue is that when methods contain "**SendRequestSync**" or "**SendRequestAsync**", the code at the receiving end cannot be tracked and included in the test coverage report.

**Comment by isc-tleavitt** [comment]
By default TestCoverage tracks coverage for the current process only. This prevents noise / pollution of stats from other concurrent use of the system. You can override this, but there are sometimes issues with the line-by-line monitor if you do; see #14 for a bit more info on this.

This answer might also be helpful: https://community.intersystems.com/post/unit-tests-and-test-coverage-intersystems-package-manager#comment-258566

**Comment by isc-tleavitt** [comment]
The plans to address this are covered in #14 so closing this issue.
