### ISSUE TITLE
Bug: TestCoverage.UI.AggregateResultViewer.cls - Divide by zero error

### ISSUE THREAD

**Issue by stevelee12** [intersystems/TestCoverage#39]
The Test Coverage results viewer will error and not display when ExecutableMethods is zero.
**File:** TestCoverage.UI.AggregateResultViewer.cls
**Suggested Fix:**
Replace line:
`ROUND(100*CoveredMethods/ExecutableMethods,2) MethodCoverage,`
with
`CASE ExecutableMethods WHEN 0 THEN NULL ELSE ROUND(100*CoveredMethods/ExecutableMethods,2) END As MethodCoverage,`

Thanks!

**Comment by isc-cge** [comment]
Could you please give more details about what the .CLS file that you're trying to see coverage data for looks like? Currently, if a .CLS file has no executable lines, TestCoverage won't monitor its coverage at all (and therefore also won't present it on the results page). I haven't been able to re-create a class that has 0 ExecutableMethods but >0 executable lines.

**Comment by stevelee12** [comment]
Hi cge,
It’s a bunch of routine .mac files, no classes

**Comment by isc-tleavitt** [comment]
Fixed in #40
